# ==================================================
#                   SERVICES
# ==================================================

services:         # Define os servicos (containers) que serao executados

  # -------------------- POSTGRES ------------------------------------------------

  postgres:                                       # Container do PostgreSQL

    container_name: postgres

    image: postgres:17.5                          # Imagem oficial do PostgreSQL

    environment:
      POSTGRES_USER: postgres                     # Usuario padrao
      POSTGRES_PASSWORD: postgres                 # Senha do banco

    volumes:
      - postgres-data:/var/lib/postgresql/data    # Persistencia dos dados

    ports:
      - "5432:5432"                               # Porta do PostgreSQL

    networks:
      - local-network                             # Rede compartilhada

  # -------------------- PGADMIN (Interface web para administrar PostgreSQL) -----

  pgadmin:

    container_name: pgadmin

    image: dpage/pgadmin4:9.5

    depends_on:
      - postgres                                    # Inicia apos postgres

    environment:
      PGADMIN_DEFAULT_EMAIL: dba@vegandelivery.com  # Login do pgAdmin
      PGADMIN_DEFAULT_PASSWORD: vegandelivery       # Senha do pgAdmin

    ports:
      - "8083:80"                                   # Acesso via navegador

    volumes:
      - pgadmin-data:/var/lib/pgadmin               # Persistencia das configs

    networks:
      - local-network

  # -------------------- KAFKA ---------------------------------------------------

  kafka:                                                                                                # Container do Apache Kafka

    container_name: kafka

    image: apache/kafka:4.1.1                                                                           # Imagem oficial do Kafka.

    ports:
      - 9092:9092                                                                                       # Expõe a porta externa do Kafka

    environment:
      KAFKA_NODE_ID: 0                                                                                  # ID único do broker/controller Kafka
      KAFKA_PROCESS_ROLES: controller,broker                                                            # Kafka atua como controller e broker ao mesmo tempo
      KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092                            # Portas/listeners internos e externos
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9090,EXTERNAL://localhost:9092                      # Endereços anunciados para conexão
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT # Protocolos de cada listener
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9091                                                      # Define quem participa do quorum do controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER                                                       # Listener usado pelo controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1                                                         # Fator de replicação do tópico interno de offsets

    volumes:
      - kafka-data:/apache/kafka                                                                        # Volume para persistência dos dados do Kafka

    networks:
      - local-network                                                                                   # Rede Docker compartilhada


  # -------------------- KAFKA UI (Interface gráfica do Kafka) --------------------
  kafka-ui:                                                                                             # Interface web para visualizar tópicos e mensagens do Kafka

    container_name: kafka-ui

    image: provectuslabs/kafka-ui:v0.7.2                                                                # Imagem do Kafka UI

    ports:
      - 8084:8080                                                                                       # Acesso via navegador em localhost:8084

    environment:
      KAFKA_CLUSTERS_0_NAME: vegandelivery-kafka-cluster                                                # Nome exibido na interface
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9090                                                     # Endereço do broker Kafka

    networks:
      - local-network                                                                                   # Rede compartilhada com Kafka

# ==================================================
#                   VOLUMES
# ==================================================

volumes:
  postgres-data: # Dados do PostgreSQL
  pgadmin-data: # Dados do pgAdmin
  kafka-data: # Dados do Kafka

# ==================================================
#                   NETWORKS
# ==================================================

networks:
  local-network:
    driver: bridge # Rede padrão Docker