server.port: 8080

#----------------------------------------

spring:
  application:
    name: delivery-tracking  # Nome da aplicação

  output:
    ansi:
      enabled: ALWAYS   # Ativa cores no console (ANSI)

  jpa:
    hibernate:
      ddl-auto: update  # Atualiza o schema automaticamente
    show-sql: false     # Mostra queries SQL no console

  datasource:
    url: jdbc:postgresql://localhost:5432/deliverydb  # URL do banco de dados do projeto
    username: postgres
    password: postgres

  kafka:
    producer:                                                                       # Configuracoes para o produtor/publicador de eventos
      bootstrap-servers: localhost:9092                                             # Endereco do broker Kafka
      key-serializer: org.apache.kafka.common.serialization.StringSerializer        # Serializa a chave da mensagem como String
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # Serializa o conteudo da mensagem em JSON
      properties:
        spring.json.type.mapping:
          delivery-placed-event:com.eriklima.vegandelivery.delivery.tracking.domain.event.DeliveryPlacedEvent,
          delivery-picked-up-event:com.eriklima.vegandelivery.delivery.tracking.domain.event.DeliveryPickUpEvent,
          delivery-fulfilled-event:com.eriklima.vegandelivery.delivery.tracking.domain.event.DeliveryFulfilledEvent

#----------------------------------------

eureka:                                             # Configurações relacionadas ao Spring Cloud com Eureka (Service Discovery).
  client:                                           # Configurações do cliente  Spring Cloud com Eureka (microserviço que vai se registrar).
    server-url:                                     # Configuração das URLs do servidor Eureka.
      default-zone: http://localhost:8761/eureka/   # Endereço do servidor Eureka onde este microserviço irá se registrar.
  instance:                                         # Configurações da instância deste microserviço no Eureka.
    instance-id: ${random.value}                    # Gera um ID aleatório para cada instância do microserviço.
    prefer-ip-address: true                         # Faz o Eureka registrar o IP da máquina em vez do hostname.

#----------------------------------------

resilience4j:                                                           # Configurações de resiliência do Resilience4j (Retry, Timeout, Circuit Breaker, etc.)

  retry:                                                                # Configurações relacionadas ao padrão Retry (tentativa automática em caso de falha

    configs:                                                            # Configurações base/reutilizáveis de Retry

      default:                                                          # Configuracao padrão de Retry que pode ser reaproveitada

        maxAttempts: 2                                                  # Define no maximo 2 tentativas totais (1 tentativa inicial + 1 nova tentativa)
        waitDuration: 20ms                                              # Define espera de 20 milissegundos entre uma tentativa e outra

    instances:                                                          # Configurações específicas para metodos/instâncias com Retry
      Retry_CourierAPIClient_payoutCalculation:                         # Nome da configuracao usada na interface "CourierAPIClient" @Retry( name = "Retry_CourierAPIClient_payoutCalculation" )

        baseConfig: default                                             # Herda configuracoes da configuracao padrao chamada "default"
        maxAttempts: 3                                                  # Sobrescreve o padrão e define até 3 tentativas totais para este método

        retryExceptions:                                                # Lista de excecoes que DEVEM disparar nova tentativa automatica
          - org.springframework.web.client.ResourceAccessException      # Faz retry quando houver erro de conexao, timeout ou indisponibilidade do servico.

        ignoreExceptions:                                               # Lista de excecoes que NAO devem tentar novamente
          - org.springframework.web.client.HttpServerErrorException     # Ignora erros HTTP do servidor (500, 502, 503, etc.) sem retry.